#!/usr/bin/env bash
# Fill in src/64-openrb150.rules from the board that is actually plugged in.
#
# The committed rule is a template (REPLACE_ME) because the OpenRB-150's USB
# ids were never read off real hardware. This reads them from a live device
# and writes a concrete rule, preferring ATTRS{serial} when the SAMD21 exposes
# one -- unlike the two CH340s (see 62-lx16a.rules), a serial number pins the
# symlink regardless of enumeration order.
#
#   bash src/openrb150_udev.sh                 # auto-detect, print the rule
#   bash src/openrb150_udev.sh /dev/ttyACM0    # be explicit
#   bash src/openrb150_udev.sh --install       # also write it + reload udev
set -euo pipefail

RULE_DST=/etc/udev/rules.d/64-openrb150.rules
RULE_SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/64-openrb150.rules"
INSTALL=0
DEV=""
for arg in "$@"; do
  case "$arg" in
    --install) INSTALL=1 ;;
    /dev/*) DEV="$arg" ;;
    *) echo "usage: $0 [/dev/ttyACMx] [--install]" >&2; exit 2 ;;
  esac
done

if [ -z "$DEV" ]; then
  # An OpenRB-150 is a CDC-ACM device; the CH340s in this robot are not, so
  # ttyACM* is already a good filter. Bail on ambiguity rather than guess.
  mapfile -t CANDIDATES < <(ls /dev/ttyACM* 2>/dev/null || true)
  if [ "${#CANDIDATES[@]}" -eq 0 ]; then
    echo "no /dev/ttyACM* found. Plug the OpenRB-150 in (USB data cable, not" >&2
    echo "a charge-only one) and check: dmesg | tail -20" >&2
    exit 1
  elif [ "${#CANDIDATES[@]}" -gt 1 ]; then
    echo "multiple ACM devices: ${CANDIDATES[*]}" >&2
    echo "unplug the others, or name one explicitly" >&2
    exit 1
  fi
  DEV="${CANDIDATES[0]}"
fi

echo "# device: $DEV"
INFO=$(udevadm info -a -n "$DEV")
VID=$(grep -m1 'ATTRS{idVendor}'  <<<"$INFO" | sed 's/.*"\(.*\)".*/\1/')
PID=$(grep -m1 'ATTRS{idProduct}' <<<"$INFO" | sed 's/.*"\(.*\)".*/\1/')
SER=$(grep -m1 'ATTRS{serial}'    <<<"$INFO" | sed 's/.*"\(.*\)".*/\1/')

if [ -z "$VID" ] || [ -z "$PID" ]; then
  echo "could not read idVendor/idProduct from $DEV" >&2
  exit 1
fi
echo "# idVendor=$VID idProduct=$PID serial=${SER:-<none>}"

# A serial that looks like a bus path (e.g. "0000:00:14.0") belongs to the USB
# controller, not the board, and would break the moment you use another port.
if [ -n "$SER" ] && [[ ! "$SER" =~ ^[0-9a-f]{4}: ]]; then
  MATCH="ATTRS{idVendor}==\"$VID\", ATTRS{idProduct}==\"$PID\", ATTRS{serial}==\"$SER\""
else
  MATCH="ATTRS{idVendor}==\"$VID\", ATTRS{idProduct}==\"$PID\""
  echo "# no usable serial number -- matching on VID/PID alone. If a second" >&2
  echo "# board with these ids is ever attached, the symlink becomes a race." >&2
fi

RULE="SUBSYSTEM==\"tty\", $MATCH, SYMLINK+=\"openrb150\", GROUP=\"dialout\", MODE=\"0660\""
echo "$RULE"

if [ "$INSTALL" -eq 1 ]; then
  # Keep the repo copy and the installed copy identical, minus the template
  # header, so the next person can see what is actually loaded.
  printf '# Generated by src/openrb150_udev.sh from %s on %s\n%s\n' \
    "$DEV" "$(date -Is)" "$RULE" | sudo tee "$RULE_DST" >/dev/null
  sudo udevadm control --reload-rules
  sudo udevadm trigger --subsystem-match=tty
  sleep 1
  if [ -e /dev/openrb150 ]; then
    echo "installed: /dev/openrb150 -> $(readlink -f /dev/openrb150)"
  else
    echo "rule installed at $RULE_DST but /dev/openrb150 did not appear;" >&2
    echo "replug the board, then: udevadm test \$(udevadm info -q path -n $DEV)" >&2
    exit 1
  fi
  echo "also update $RULE_SRC so the repo stops carrying REPLACE_ME"
fi
